research_task:
  description: >
    Determine the carbon footprint for the specified product: {query}.
    Emphasize returning a clear, consolidated value.
  agent: milvus_researcher
  expected_output: >
    A single, clear carbon footprint metric for the product, formatted as:
    "[value] [emission unit] per [product unit], confidence: [score]"
    Example: "2.5 kg CO₂e per kg, confidence: 0.85"
  output_file: researcher.txt

discovery_research_task:
  description: >
    Given a product-related query: {query}, find the carbon footprint using Watson Discovery.
    Return:
    - Carbon footprint value
    - Emission unit (e.g., kg CO₂e)
    - Product unit (e.g., per item, per 100g)
    - Confidence score (between 0 and 1)
  agent: discovery_researcher
  expected_output: >
    "[value] [emission unit] per [product unit], confidence: [score]"
    Example: "1.8 kg CO₂e per 100g, confidence: 0.87"
  output_file: discovery_result.txt

analysis_task:
  description: >
    Analyze the research findings about carbon footprint for query: {query}
    Consider multiple factors and provide quantitative analysis where possible.
  agent: analyst
  expected_output: >
    An analytical report containing:
    1. Key findings and patterns
    2. Statistical analysis
    3. Comparative analysis
    4. Recommendations
  output_file: analyst.txt

formatting_task:
  description: >
    Format the research and analysis findings into a clear, structured response.
    Make the information accessible and easy to understand.
  agent: formatter
  expected_output: >
    A well-formatted response with:
    1. Clear sections and headings
    2. Key points highlighted
    3. Data presented in readable format
    4. Visual elements (if applicable)
  output_file: formatter.txt

# compilation_task:
#   description: >
#     Compile all findings into a final comprehensive response.
#     Ensure all key information is included and properly attributed.
#   agent: compiler
#   expected_output: >
#     A complete response containing:
#     1. Main findings and conclusions
#     2. Supporting data and analysis
#     3. Sources and references
#     4. Confidence levels
#   output_file: final_report.txt