research_task:
  description: >
    Research information about the carbon footprint impact based on the following query: {query}
    Focus on finding accurate, verifiable data from our knowledge base and trusted sources.
  agent: researcher
  expected_output: >
    A detailed research report containing:
    1. Primary carbon footprint data
    2. Environmental impact statistics
    3. Sources and references
    4. Confidence levels in the data
  output_file: researcher.txt

analysis_task:
  description: >
    Analyze the research findings about carbon footprint for query: {query}
    Consider multiple factors and provide quantitative analysis where possible.
  agent: analyst
  expected_output: >
    An analytical report containing:
    1. Key findings and patterns
    2. Statistical analysis
    3. Comparative analysis
    4. Recommendations
  output_file: analyst.txt

formatting_task:
  description: >
    Format the research and analysis findings into a clear, structured response.
    Make the information accessible and easy to understand.
  agent: formatter
  expected_output: >
    A well-formatted response with:
    1. Clear sections and headings
    2. Key points highlighted
    3. Data presented in readable format
    4. Visual elements (if applicable)
  output_file: formatter.txt

compilation_task:
  description: >
    Compile all findings into a final comprehensive response.
    Ensure all key information is included and properly attributed.
  agent: compiler
  expected_output: >
    A complete response containing:
    1. Main findings and conclusions
    2. Supporting data and analysis
    3. Sources and references
    4. Confidence levels
  output_file: final_report.txt